version: '3'
services:
  app:
    image: dyoshikawa/laravel:latest
    volumes:
      - .:/myproject:cached
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db-data:/var/lib/postgresql/data:cached
    ports:
      - 5432:5432
